<template>
  <div class="main-page">
    <MainHeader></MainHeader>
    <div>
      <section class="fullscreen-mainpage-section">
        <div class="logo-container">
          <img src="@/assets/logo.png" alt="Logo" class="logo" />
        </div>
        <h1 style="margin-left: 20px;">scMoAnno: A Pre-trained Cell Type Annotation Method for Single-cell Multi-omics Data</h1>
        <div class="scroll-indicator">
          <el-icon><ArrowDownBold /></el-icon>
        </div>
      </section>
      <section class="intro-section">
        <div class="intro-container">
          <div class="intro-text">
            <p> Cell type annotation is paramount for subsequent biomedical research endeavors. Recently, supervised
              classification methods based on deep learning have demonstrated significant advancements in cell type
              annotation. However, challenges persist regarding how to efficiently leverage single-cell multi omics data
              for cell type annotation and interpretation and how to endow models with adaptive generalization
              capabilities for efficient identification of rare cell types. We introduce scMoAnno, a methodology for
              cell type annotation based on single-cell multi-omics data. Leveraging pre trained cross-attention
              networks, scMoAnno facilitates efficient mutual learning and fusion of genetic and epigenetic
              distributions in single-cell multi-omics data, enabling precise cell type annotation. Predictions
              conducted by scMoAnno on single-cell RNA sequencing (scRNA-seq) and single-cell assay for
              transposase-accessible chromatin sequencing (scATAC-seq) data demonstrate enhanced generalization capacity
              for the recognition of rare cell types through pre-trained feature fusion extraction and training of
              classifiers based on fused data inputs. Rigorously conducted experiments on four meticulously curated
              benchmark datasets illustrate that scMoAnno surpasses nine other state-of the-art baseline models in
              overall performance. Furthermore, the increase in clustering scores, fused with multi-omics data and
              extracted by scMoAnno, is elucidated from the perspective of promoting downstream analysis of single
              cells, explaining how our model’s enhancement of cell type annotation performance yields positive effects.
              <hr>
              The workflow diagram of the single-cell multi-omics cell type annotation algorithm, scMoAnno. The scMoAnno
              model
              undergoes two rounds of supervised learning. In the first round, a pre-trained fusion feature extractor is
              utilized to perform
              cross-attention feature extraction on scRNA-seq and scATAC-seq data, encoding the interaction features of
              the two modalities.
              In the second round, using the feature data generated by the pre-trained feature extractor, a
              Transformer-based fusion data cell
              type annotation module is introduced to achieve the precise assignment of cell types.
            </p>
          </div>
          <div class="intro-image">
            <img src="@/assets/model.png" alt="介绍图片" />
          </div>
        </div>
      </section>
      <section class="intro-section">
        <div class="intro-container">
          <div class="intro-text">
            <h1></h1>
            <p> In Table, the scMoAnno method outperformed the baseline comparison methods regarding accuracy
              metrics. Compared to the best-performing base line method CIForm in terms of accuracy, the scMoAnno method
              achieved a 2% improvement in accuracy. In terms of balanced accuracy
              metrics, it reached a balanced accuracy of 90%, which was on par with the best-performing base line
              method, scTransSort. Thus, this validates the feasibility and effectiveness of the proposed
              methodinthisstudy.
            </p>
          </div>
          <div class="intro-image">
            <img src="@/assets/data.png" alt="介绍图片" />
          </div>
        </div>
      </section>
    </div>
  </div>
</template>

<script>
import MainHeader from "../components/MainHeader.vue"
export default {
  name: 'HomeView',
  components: {
    MainHeader
  }
}
</script>